#!/usr/bin/env bash
# Usage: ./0-world_wide_web <domain> [<subdomain>]
# Display information about subdomains.

# Function to get domain information
domain_information () {
    result=$(dig "$2"."$1" +short)
    if [ -z "$result" ]; then
        echo "No DNS record found for $2.$1"
    else
        record_type=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -n1 | awk '{print $4}')
        echo "The subdomain $2.$1 is a $record_type record and points to $result"
    fi
}

# Check the number of arguments
if [ "$#" -eq 1 ]; then
  domain_information "$1" "www"
  domain_information "$1" "lb-01"
  domain_information "$1" "web-01"
  domain_information "$1" "web-02"
elif [ "$#" -eq 2 ]; then
  domain_information "$1" "$2"
else
  echo "Usage: $0 <domain> [<subdomain>]"
fi

