#!/usr/bin/env bash
# stops the 4-to_infinity_and_beyond process.

./4-to_infinity_and_beyond & pid=$(pgrep -f "4-to_infinity_and_beyond"); while ps -p $pid > /dev/null; do :; done; echo "Terminated"
